#!/usr/bin/env bash

set -eux

common_flags="-arch arm64 -arch x86_64 -mmacosx-version-min=10.9"

export CC=$(which clang)
export CXX=$(which clang++)
export CFLAGS="${common_flags} -std=gnu11"
export CXXFLAGS="${common_flags} -std=gnu++14"
export LDFLAGS="-mmacosx-version-min=10.9"

pushd cmake
./build-cmake.sh
popd

pushd swig
./build-swig.sh
popd

pushd ncurses
./build-ncurses.sh
popd

pushd libedit
./build-libedit.sh
popd

export -n CC
export -n CXX
export -n CFLAGS
export -n CXXFLAGS
export -n LDFLAGS

unset CC
unset CXX
unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

pushd re2c
./build-re2c.sh
popd

pushd ninja
./build-ninja.sh
popd

pushd tbb
./build-tbb.sh
popd
