#!/usr/bin/env bash

if [[ "${XCTOOLCHAIN}" = "" ]]; then
  XCTOOLCHAIN=XcodeDefault
fi

export XCTOOLCHAIN

set -eux

pushd "$(dirname ${0})"
path=$(pwd)
trap 'rm -rf "${path}/build_deps"' INT TERM HUP

export install_prefix=$(pwd)/build/deps
if [[ -d "${install_prefix}" ]]; then
  rm -rf "${install_prefix}"
fi

common_flags="-arch arm64 -arch x86_64 -mmacosx-version-min=10.9"

export CC="xcrun --toolchain ${XCTOOLCHAIN} --sdk macosx clang"
export CXX="xcrun --toolchain ${XCTOOLCHAIN} --sdk macosx clang++"

export CFLAGS="${common_flags} -std=gnu11"
export CXXFLAGS="${common_flags} -std=gnu++14"
export LDFLAGS="-mmacosx-version-min=10.9 -Wl,-rpath,@executable_path/../lib"

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

pushd python3
./build-python3.sh
popd

pushd swig
./build-swig.sh
popd

pushd ncurses
./build-ncurses.sh
popd

pushd readline
./build-readline.sh
popd

pushd libedit
./build-libedit.sh
popd

pushd cmake
./build-cmake.sh
popd

export -n CC
export -n CXX

export -n CFLAGS
export -n CXXFLAGS
export -n LDFLAGS

unset CC
unset CXX

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

export PATH=${install_prefix}/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

pushd re2c
./build-re2c.sh
popd

pushd ninja
./build-ninja.sh
popd

pushd tbb
./build-tbb.sh
popd

pushd zstd
./build-zstd.sh
popd

export -n install_prefix

unset install_prefix

popd

export -n XCTOOLCHAIN
unset XCTOOLCHAIN
