#!/usr/bin/env bash

set -eux

pushd "$(dirname ${0})"

install_prefix=$(pwd)/build_deps/local
export install_prefix

common_flags="-arch arm64 -arch x86_64 -mmacosx-version-min=10.9"

export CC="xcrun --sdk macosx clang"
export CXX="xcrun --sdk macosx clang++"
export CFLAGS="${common_flags} -std=gnu11"
export CXXFLAGS="${common_flags} -std=gnu++14"
export LDFLAGS="-mmacosx-version-min=10.9"

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

pushd cmake
./build-cmake.sh
popd

export PATH=${install_prefix}/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

pushd ninja
./build-ninja.sh
popd

pushd re2c
./build-re2c.sh
popd

pushd swig
./build-swig.sh
popd

pushd ncurses
./build-ncurses.sh
popd

pushd libedit
./build-libedit.sh
popd

export -n CC
export -n CXX
export -n CFLAGS
export -n CXXFLAGS
export -n LDFLAGS

unset CC
unset CXX
unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

pushd tbb
./build-tbb.sh
popd

pushd zstd
./build-zstd.sh
popd

export -n install_prefix

unset install_prefix

popd